kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: mayhem-control
  labels:
    app: mayhem-control
    app.kubernetes.io/component: mayhem-control
    app.kubernetes.io/instance: mayhem-control
    app.kubernetes.io/name: mayhem-control
    app.kubernetes.io/part-of: mayhem
    app.openshift.io/runtime: java
    app.openshift.io/runtime-version: openjdk-17-ubi8
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'mayhem-control:latest'
  resources: {}
  successfulBuildsHistoryLimit: 3
  failedBuildsHistoryLimit: 1
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'java:openjdk-17-ubi8'
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/glroland/mayhem.git'
    contextDir: /mayhem-control
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: mayhem-control-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: mayhem-control-github-webhook-secret
    - type: ImageChange
      imageChange: {}
    - type: ConfigChange
  runPolicy: Serial
